import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Sidebar from "@/components/Sidebar/Sidebar";




const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ⭐️ 1. لا تحتاج h-screen على html إذا كانت على body ⭐️
    <html lang="en" className={geistMono.variable}> 
      {/* ⭐️ 2. Body: flex-col و min-h-screen لضمان الارتفاع العمودي ⭐️ */}
      <body className="flex flex-col min-h-screen"> 
        
        <Navbar/>
      
        {/* ⭐️ 3. الحاوية الجديدة: يجب أن تجمع Sidebar و Children ⭐️ 
           * flex: لجعل المكونات تجلس بجانب بعضها (أفقيًا).
           * flex-grow: لتمتد هذه الحاوية وتملأ الفراغ المتبقي بين Navbar و Footer.
        */}
        <div className="flex w-full flex-grow"> 
          
          {/* 4. Sidebar Container: نجعله ثابتًا على اليسار ويمتد عموديًا */}
          {/* تم إضافة h-full و sticky top-0 ليعمل ضمن flex-grow */}
          <div className="w-72 bg-white shadow-xl border-r border-gray-100 hidden lg:block sticky top-0 h-full overflow-y-auto">
             
            <Sidebar/>
          </div>
          

          {/* 5. Content Area: يأخذ المساحة المتبقية */}
          <main className="flex-grow py-8 px-6 overflow-y-auto"> 
            <div className="container mx-auto">
              {children} 
            </div>
          </main>
          
        </div> 
        
        <Footer/>
      </body>
    </html>
  );
}